In [1]:
from pathlib import Path

In [2]:
# Find the Component_4 project directory
PROJECT_DIR = Path.cwd().parent

print("Notebook location:", Path.cwd())
print("Project directory:", PROJECT_DIR)
print("Project directory exists:", PROJECT_DIR.exists())

Notebook location: c:\Users\User\OneDrive\Desktop\Research\Agentic-AI-Based-Market-Intelligence-Framework-For-Bitcoin-and-Ethereum-Trading\Component_4\notebooks
Project directory: c:\Users\User\OneDrive\Desktop\Research\Agentic-AI-Based-Market-Intelligence-Framework-For-Bitcoin-and-Ethereum-Trading\Component_4
Project directory exists: True

In [3]:
RAW_DATA_DIR = PROJECT_DIR / "data" / "raw"

In [4]:
BTC_FILE = RAW_DATA_DIR / "BTCUSDT.csv"
ETH_FILE = RAW_DATA_DIR / "ETHUSDT.csv"

print("BTC file exists:", BTC_FILE.exists())
print("ETH file exists:", ETH_FILE.exists())
print("Raw data directory:", RAW_DATA_DIR)

BTC file exists: True
ETH file exists: True
Raw data directory: c:\Users\User\OneDrive\Desktop\Research\Agentic-AI-Based-Market-Intelligence-Framework-For-Bitcoin-and-Ethereum-Trading\Component_4\data\raw

In [5]:
print(f"BTC file size: {BTC_FILE.stat().st_size / (1024**3):.2f} GB")
print(f"ETH file size: {ETH_FILE.stat().st_size / (1024**3):.2f} GB")

BTC file size: 0.67 GB
ETH file size: 0.65 GB

In [6]:
import pandas as pd

btc_columns = pd.read_csv(BTC_FILE, nrows=0).columns.tolist()
eth_columns = pd.read_csv(ETH_FILE, nrows=0).columns.tolist()

print("BTC columns:")
print(btc_columns)

print("\nETH columns:")
print(eth_columns)

print("\nSame columns:", btc_columns == eth_columns)

BTC columns:
['open', 'high', 'low', 'close', 'volume', 'quote_volume', 'num_trades', 'taker_buy_base_vol', 'taker_buy_quote_vol', 'timestamp_utc', 'taker_sell_base_vol', 'taker_sell_quote_vol', 'mark_open', 'mark_high', 'mark_low', 'mark_close', 'index_open', 'index_high', 'index_low', 'index_close']

ETH columns:
['open', 'high', 'low', 'close', 'volume', 'quote_volume', 'num_trades', 'taker_buy_base_vol', 'taker_buy_quote_vol', 'timestamp_utc', 'taker_sell_base_vol', 'taker_sell_quote_vol', 'mark_open', 'mark_high', 'mark_low', 'mark_close', 'index_open', 'index_high', 'index_low', 'index_close']

Same columns: True

In [7]:
btc_sample = pd.read_csv(BTC_FILE, nrows=5)
eth_sample = pd.read_csv(ETH_FILE, nrows=5)

display(btc_sample)
display(eth_sample)

,open,high,low,close,volume,quote_volume,num_trades,taker_buy_base_vol,taker_buy_quote_vol,timestamp_utc,taker_sell_base_vol,taker_sell_quote_vol,mark_open,mark_high,mark_low,mark_close,index_open,index_high,index_low,index_close
0,7189.43,7190.52,7177.00,7182.44,246.092,1.767430e+06,336,46.630,334813.19820,2020-01-01 00:00:00+00:00,199.462,1.432617e+06,7195.365819,7195.365819,7185.821968,7186.832937,7195.365819,7195.974910,7186.708547,7188.242183
1,7182.43,7182.44,7178.75,7179.01,70.909,5.091458e+05,140,32.597,234063.27884,2020-01-01 00:01:00+00:00,38.312,2.750825e+05,7187.355631,7188.351086,7185.515767,7186.446199,7188.714910,7189.237638,7186.400365,7187.135365
2,7179.01,7179.01,7175.25,7177.93,99.420,7.135396e+05,148,16.311,117066.92118,2020-01-01 00:02:00+00:00,83.109,5.964726e+05,7186.250800,7186.250800,7182.968351,7183.254896,7186.949001,7186.949001,7183.850909,7184.191818
3,7177.77,7182.60,7177.00,7181.11,69.330,4.977934e+05,104,43.723,313920.02981,2020-01-01 00:03:00+00:00,25.607,1.838733e+05,7183.309465,7187.865179,7183.309465,7187.620756,7184.314545,7188.746364,7184.314545,7188.127273
4,7179.10,7179.10,7172.94,7175.25,97.368,6.986274e+05,193,36.616,262734.68999,2020-01-01 00:04:00+00:00,60.752,4.358927e+05,7187.246287,7187.246287,7180.290260,7180.422124,7187.568182,7187.568182,7181.168636,7181.314091

,open,high,low,close,volume,quote_volume,num_trades,taker_buy_base_vol,taker_buy_quote_vol,timestamp_utc,taker_sell_base_vol,taker_sell_quote_vol,mark_open,mark_high,mark_low,mark_close,index_open,index_high,index_low,index_close
0,129.12,129.12,128.91,128.97,289.040,37296.67223,18,155.107,20005.44348,2020-01-01 00:00:00+00:00,133.933,17291.22875,129.149636,129.179051,129.020013,129.036012,129.149636,129.166136,129.007136,129.023136
1,128.95,129.04,128.93,128.94,695.566,89717.06489,49,284.536,36703.77497,2020-01-01 00:01:00+00:00,411.030,53013.28992,129.036012,129.101554,129.030463,129.052623,129.023136,129.088682,129.017591,129.039773
2,128.93,128.97,128.92,128.92,131.902,17008.70674,17,107.865,13908.75485,2020-01-01 00:02:00+00:00,24.037,3099.95189,129.052623,129.052623,128.998682,129.003228,129.039773,129.039773,128.985864,128.989045
3,128.97,128.98,128.93,128.96,455.572,58748.97547,19,306.033,39464.28873,2020-01-01 00:03:00+00:00,149.539,19284.68674,129.001864,129.037843,128.991404,129.035113,128.989045,129.025045,128.978591,129.008682
4,128.95,128.95,128.76,128.81,866.117,111594.84023,48,273.595,35249.08931,2020-01-01 00:04:00+00:00,592.522,76345.75092,129.021475,129.021475,128.890346,128.892163,128.998273,128.998273,128.877591,128.903045

In [8]:
#check for missing values
numeric_columns = [
    "open", "high", "low", "close",
    "volume", "quote_volume", "num_trades",
    "taker_buy_base_vol", "taker_buy_quote_vol",
    "taker_sell_base_vol", "taker_sell_quote_vol",
    "mark_open", "mark_high", "mark_low", "mark_close",
    "index_open", "index_high", "index_low", "index_close"
]

print("BTC missing values in sample:")
print(btc_sample[numeric_columns].isna().sum())

print("\nETH missing values in sample:")
print(eth_sample[numeric_columns].isna().sum())

BTC missing values in sample:
open                    0
high                    0
low                     0
close                   0
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
mark_open               0
mark_high               0
mark_low                0
mark_close              0
index_open              0
index_high              0
index_low               0
index_close             0
dtype: int64

ETH missing values in sample:
open                    0
high                    0
low                     0
close                   0
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
mark_open               0
mark_high               0
mark_low                0
mark_close              0
index_open              0
index_high              0
index_low               0
index_close             0
dtype: int64

In [9]:
import numpy as np
import pandas as pd

NUMERIC_COLUMNS = [
    "open", "high", "low", "close",
    "volume", "quote_volume", "num_trades",
    "taker_buy_base_vol", "taker_buy_quote_vol",
    "taker_sell_base_vol", "taker_sell_quote_vol",
    "mark_open", "mark_high", "mark_low", "mark_close",
    "index_open", "index_high", "index_low", "index_close"
]

VOLUME_COLUMNS = [
    "volume", "quote_volume", "num_trades",
    "taker_buy_base_vol", "taker_buy_quote_vol",
    "taker_sell_base_vol", "taker_sell_quote_vol"
]

def validate_raw_csv(file_path, chunk_size=200_000):
    total_rows = 0
    missing = pd.Series(0, index=NUMERIC_COLUMNS, dtype="int64")
    non_finite = pd.Series(0, index=NUMERIC_COLUMNS, dtype="int64")

    invalid_ohlc = 0
    negative_activity = pd.Series(0, index=VOLUME_COLUMNS, dtype="int64")
    invalid_timestamps = 0
    first_timestamp = None
    last_timestamp = None

    for chunk in pd.read_csv(file_path, chunksize=chunk_size):
        total_rows += len(chunk)

        # Check numeric columns
        numeric = chunk[NUMERIC_COLUMNS].apply(
            pd.to_numeric, errors="coerce"
        )

        missing += numeric.isna().sum().astype("int64")

        non_finite += pd.Series({
            col: int(np.isinf(numeric[col].dropna()).sum())
            for col in NUMERIC_COLUMNS
        })

        # Check basic OHLC consistency
        price_cols = ["open", "high", "low", "close"]
        prices = numeric[price_cols]

        invalid = (
            (prices["high"] < prices[["open", "low", "close"]].max(axis=1))
            | (prices["low"] > prices[["open", "high", "close"]].min(axis=1))
            | (prices <= 0).any(axis=1)
        )
        invalid_ohlc += int(invalid.sum())

        # Negative activity values
        negative_activity += (
            numeric[VOLUME_COLUMNS] < 0
        ).sum().astype("int64")

        # Timestamp parsing and coverage boundaries
        ts = pd.to_datetime(chunk["timestamp_utc"], utc=True, errors="coerce")
        invalid_timestamps += int(ts.isna().sum())

        valid_ts = ts.dropna()
        if not valid_ts.empty:
            if first_timestamp is None:
                first_timestamp = valid_ts.iloc[0]
            last_timestamp = valid_ts.iloc[-1]

    return {
        "file": str(file_path),
        "total_rows": total_rows,
        "first_timestamp": first_timestamp,
        "last_timestamp": last_timestamp,
        "missing_numeric_values": missing,
        "non_finite_numeric_values": non_finite,
        "invalid_ohlc_rows": invalid_ohlc,
        "negative_activity_values": negative_activity,
        "invalid_timestamps": invalid_timestamps,
    }

In [10]:
btc_report = validate_raw_csv(BTC_FILE)

print("BTC total rows:", btc_report["total_rows"])
print("BTC first timestamp:", btc_report["first_timestamp"])
print("BTC last timestamp:", btc_report["last_timestamp"])
print("BTC invalid OHLC rows:", btc_report["invalid_ohlc_rows"])
print("BTC invalid timestamps:", btc_report["invalid_timestamps"])

print("\nMissing numeric values:")
print(btc_report["missing_numeric_values"])

print("\nNon-finite numeric values:")
print(btc_report["non_finite_numeric_values"])

print("\nNegative activity values:")
print(btc_report["negative_activity_values"])

BTC total rows: 2980800
BTC first timestamp: 2020-01-01 00:00:00+00:00
BTC last timestamp: 2025-08-31 23:59:00+00:00
BTC invalid OHLC rows: 0
BTC invalid timestamps: 0

Missing numeric values:
open                        0
high                        0
low                         0
close                       0
volume                      0
quote_volume                0
num_trades                  0
taker_buy_base_vol          0
taker_buy_quote_vol         0
taker_sell_base_vol         0
taker_sell_quote_vol        0
mark_open               11575
mark_high               11575
mark_low                11575
mark_close              11575
index_open              17340
index_high              17340
index_low               17340
index_close             17340
dtype: int64

Non-finite numeric values:
open                    0
high                    0
low                     0
close                   0
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
mark_open               0
mark_high               0
mark_low                0
mark_close              0
index_open              0
index_high              0
index_low               0
index_close             0
dtype: int64

Negative activity values:
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
dtype: int64

In [11]:
eth_report = validate_raw_csv(ETH_FILE)

print("ETH total rows:", eth_report["total_rows"])
print("ETH first timestamp:", eth_report["first_timestamp"])
print("ETH last timestamp:", eth_report["last_timestamp"])
print("ETH invalid OHLC rows:", eth_report["invalid_ohlc_rows"])
print("ETH invalid timestamps:", eth_report["invalid_timestamps"])

print("\nMissing numeric values:")
print(eth_report["missing_numeric_values"])

print("\nNon-finite numeric values:")
print(eth_report["non_finite_numeric_values"])

print("\nNegative activity values:")
print(eth_report["negative_activity_values"])

ETH total rows: 2980800
ETH first timestamp: 2020-01-01 00:00:00+00:00
ETH last timestamp: 2025-08-31 23:59:00+00:00
ETH invalid OHLC rows: 0
ETH invalid timestamps: 0

Missing numeric values:
open                       0
high                       0
low                        0
close                      0
volume                     0
quote_volume               0
num_trades                 0
taker_buy_base_vol         0
taker_buy_quote_vol        0
taker_sell_base_vol        0
taker_sell_quote_vol       0
mark_open               2946
mark_high               2946
mark_low                2946
mark_close              2946
index_open              4381
index_high              4381
index_low               4381
index_close             4381
dtype: int64

Non-finite numeric values:
open                    0
high                    0
low                     0
close                   0
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
mark_open               0
mark_high               0
mark_low                0
mark_close              0
index_open              0
index_high              0
index_low               0
index_close             0
dtype: int64

Negative activity values:
volume                  0
quote_volume            0
num_trades              0
taker_buy_base_vol      0
taker_buy_quote_vol     0
taker_sell_base_vol     0
taker_sell_quote_vol    0
dtype: int64

In [12]:
def check_timestamp_integrity(file_path, chunk_size=200_000):
    previous_timestamp = None
    total_rows = 0
    duplicate_timestamps = 0
    non_minute_gaps = 0
    first_timestamp = None
    last_timestamp = None

    for chunk in pd.read_csv(
        file_path,
        usecols=["timestamp_utc"],
        chunksize=chunk_size
    ):
        timestamps = pd.to_datetime(
            chunk["timestamp_utc"],
            utc=True,
            errors="coerce"
        )

        total_rows += len(timestamps)

        if timestamps.isna().any():
            raise ValueError("Invalid timestamps found.")

        duplicate_timestamps += int(timestamps.duplicated().sum())

        if first_timestamp is None and len(timestamps):
            first_timestamp = timestamps.iloc[0]

        if previous_timestamp is not None and len(timestamps):
            if timestamps.iloc[0] <= previous_timestamp:
                raise ValueError(
                    "Timestamps are not strictly increasing across chunks."
                )

            differences = timestamps.diff()
            differences.iloc[0] = (
                timestamps.iloc[0] - previous_timestamp
            )

            non_minute_gaps += int(
                (differences != pd.Timedelta(minutes=1)).sum()
            )

        elif len(timestamps):
            differences = timestamps.diff().iloc[1:]
            non_minute_gaps += int(
                (differences != pd.Timedelta(minutes=1)).sum()
            )

        if len(timestamps):
            previous_timestamp = timestamps.iloc[-1]
            last_timestamp = previous_timestamp

    return {
        "total_rows": total_rows,
        "first_timestamp": first_timestamp,
        "last_timestamp": last_timestamp,
        "duplicate_timestamps": duplicate_timestamps,
        "non_minute_intervals": non_minute_gaps,
    }

In [13]:
btc_time_check = check_timestamp_integrity(BTC_FILE)
eth_time_check = check_timestamp_integrity(ETH_FILE)

print("BTC:", btc_time_check)
print("\nETH:", eth_time_check)

BTC: {'total_rows': 2980800, 'first_timestamp': Timestamp('2020-01-01 00:00:00+0000', tz='UTC'), 'last_timestamp': Timestamp('2025-08-31 23:59:00+0000', tz='UTC'), 'duplicate_timestamps': 0, 'non_minute_intervals': 0}

ETH: {'total_rows': 2980800, 'first_timestamp': Timestamp('2020-01-01 00:00:00+0000', tz='UTC'), 'last_timestamp': Timestamp('2025-08-31 23:59:00+0000', tz='UTC'), 'duplicate_timestamps': 0, 'non_minute_intervals': 0}

In [14]:
import numpy as np
import pandas as pd

NUMERIC_COLUMNS = [
    "open", "high", "low", "close",
    "volume", "quote_volume", "num_trades",
    "taker_buy_base_vol", "taker_buy_quote_vol",
    "taker_sell_base_vol", "taker_sell_quote_vol",
    "mark_open", "mark_high", "mark_low", "mark_close",
    "index_open", "index_high", "index_low", "index_close",
]

def check_numeric_quality(file_path, chunk_size=200_000):
    results = {
        "total_rows": 0,
        "missing_values": {},
        "non_finite_values": {},
        "negative_activity_values": {},
        "invalid_ohlc_rows": 0,
    }

    activity_columns = [
        "volume", "quote_volume", "num_trades",
        "taker_buy_base_vol", "taker_buy_quote_vol",
        "taker_sell_base_vol", "taker_sell_quote_vol",
    ]

    for col in NUMERIC_COLUMNS:
        results["missing_values"][col] = 0
        results["non_finite_values"][col] = 0

    for col in activity_columns:
        results["negative_activity_values"][col] = 0

    for chunk in pd.read_csv(
        file_path,
        usecols=NUMERIC_COLUMNS,
        chunksize=chunk_size,
    ):
        results["total_rows"] += len(chunk)

        for col in NUMERIC_COLUMNS:
            values = pd.to_numeric(chunk[col], errors="coerce")

            results["missing_values"][col] += int(
                values.isna().sum()
            )

            results["non_finite_values"][col] += int(
                np.isinf(values).sum()
            )

        for col in activity_columns:
            values = pd.to_numeric(chunk[col], errors="coerce")

            results["negative_activity_values"][col] += int(
                (values < 0).sum()
            )

        ohlc = chunk[["open", "high", "low", "close"]].apply(
            pd.to_numeric, errors="coerce"
        )

        invalid_ohlc = (
            (ohlc["high"] < ohlc["low"])
            | (ohlc["high"] < ohlc[["open", "close"]].max(axis=1))
            | (ohlc["low"] > ohlc[["open", "close"]].min(axis=1))
        )

        results["invalid_ohlc_rows"] += int(invalid_ohlc.sum())

    return results

In [15]:
btc_quality = check_numeric_quality(BTC_FILE)
eth_quality = check_numeric_quality(ETH_FILE)

print("BTC NUMERIC QUALITY")
print(btc_quality)

print("\nETH NUMERIC QUALITY")
print(eth_quality)

BTC NUMERIC QUALITY
{'total_rows': 2980800, 'missing_values': {'open': 0, 'high': 0, 'low': 0, 'close': 0, 'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0, 'mark_open': 11575, 'mark_high': 11575, 'mark_low': 11575, 'mark_close': 11575, 'index_open': 17340, 'index_high': 17340, 'index_low': 17340, 'index_close': 17340}, 'non_finite_values': {'open': 0, 'high': 0, 'low': 0, 'close': 0, 'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0, 'mark_open': 0, 'mark_high': 0, 'mark_low': 0, 'mark_close': 0, 'index_open': 0, 'index_high': 0, 'index_low': 0, 'index_close': 0}, 'negative_activity_values': {'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0}, 'invalid_ohlc_rows': 0}

ETH NUMERIC QUALITY
{'total_rows': 2980800, 'missing_values': {'open': 0, 'high': 0, 'low': 0, 'close': 0, 'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0, 'mark_open': 2946, 'mark_high': 2946, 'mark_low': 2946, 'mark_close': 2946, 'index_open': 4381, 'index_high': 4381, 'index_low': 4381, 'index_close': 4381}, 'non_finite_values': {'open': 0, 'high': 0, 'low': 0, 'close': 0, 'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0, 'mark_open': 0, 'mark_high': 0, 'mark_low': 0, 'mark_close': 0, 'index_open': 0, 'index_high': 0, 'index_low': 0, 'index_close': 0}, 'negative_activity_values': {'volume': 0, 'quote_volume': 0, 'num_trades': 0, 'taker_buy_base_vol': 0, 'taker_buy_quote_vol': 0, 'taker_sell_base_vol': 0, 'taker_sell_quote_vol': 0}, 'invalid_ohlc_rows': 0}

In [16]:
import json
from pathlib import Path
from datetime import datetime, timezone

REPORT_DIR = PROJECT_DIR / "reports" / "data_validation"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

validation_report = {
    "validation_date_utc": datetime.now(timezone.utc).isoformat(),
    "datasets": {
        "BTCUSDT": {
            "timestamp_validation": btc_time_check,
            "numeric_quality": btc_quality,
        },
        "ETHUSDT": {
            "timestamp_validation": eth_time_check,
            "numeric_quality": eth_quality,
        },
    },
}

# Convert Pandas timestamps into JSON-compatible strings.
def json_serializer(value):
    if isinstance(value, (pd.Timestamp,)):
        return value.isoformat()
    raise TypeError(f"Unsupported type: {type(value).__name__}")

report_path = REPORT_DIR / "raw_data_validation_report.json"

with open(report_path, "w", encoding="utf-8") as file:
    json.dump(
        validation_report,
        file,
        indent=4,
        default=json_serializer,
    )

print("Validation report saved:", report_path)
print("File exists:", report_path.exists())

Validation report saved: c:\Users\User\OneDrive\Desktop\Research\Agentic-AI-Based-Market-Intelligence-Framework-For-Bitcoin-and-Ethereum-Trading\Component_4\reports\data_validation\raw_data_validation_report.json
File exists: True

In [17]:

from pathlib import Path
import numpy as np
import pandas as pd

PROJECT_DIR = Path.cwd().parent

RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"

DATASETS = {
    "BTCUSDT": (
        RAW_DIR / "BTCUSDT.csv",
        PROCESSED_DIR / "BTCUSDT_1m_preprocessed.csv",
    ),
    "ETHUSDT": (
        RAW_DIR / "ETHUSDT.csv",
        PROCESSED_DIR / "ETHUSDT_1m_preprocessed.csv",
    ),
}

def validate_preprocessed_file(
    symbol, raw_path, processed_path, chunk_size=200_000
):
    print(f"\nValidating {symbol}...")

    raw_reader = pd.read_csv(raw_path, chunksize=chunk_size)
    processed_reader = pd.read_csv(
        processed_path, chunksize=chunk_size
    )

    total_rows = 0

    try:
        for raw_chunk, processed_chunk in zip(
            raw_reader, processed_reader, strict=True
        ):
            # Confirm identical columns and order.
            if list(raw_chunk.columns) != list(
                processed_chunk.columns
            ):
                raise ValueError("Column mismatch detected.")

            if len(raw_chunk) != len(processed_chunk):
                raise ValueError("Chunk row count mismatch.")

            # Compare timestamps after UTC conversion.
            raw_ts = pd.to_datetime(
                raw_chunk["timestamp_utc"], utc=True
            )
            processed_ts = pd.to_datetime(
                processed_chunk["timestamp_utc"], utc=True
            )

            if not raw_ts.equals(processed_ts):
                raise ValueError("Timestamp mismatch detected.")

            # Compare numeric values without filling missing data.
            numeric_columns = [
                col for col in raw_chunk.columns
                if col != "timestamp_utc"
            ]

            for col in numeric_columns:
                raw_values = pd.to_numeric(
                    raw_chunk[col], errors="raise"
                ).to_numpy(dtype=float, na_value=np.nan)

                processed_values = pd.to_numeric(
                    processed_chunk[col], errors="raise"
                ).to_numpy(dtype=float, na_value=np.nan)

                if not np.allclose(
                    raw_values,
                    processed_values,
                    rtol=1e-12,
                    atol=1e-12,
                    equal_nan=True,
                ):
                    raise ValueError(
                        f"Data mismatch in column: {col}"
                    )

            total_rows += len(raw_chunk)

    finally:
        raw_reader.close()
        processed_reader.close()

    print(f"Rows compared: {total_rows:,}")
    print("Columns: PASS")
    print("Timestamps: PASS")
    print("Numeric values: PASS")
    print(f"{symbol}: VALIDATION PASSED")

for symbol, (raw_path, processed_path) in DATASETS.items():
    validate_preprocessed_file(
        symbol, raw_path, processed_path
    )

Validating BTCUSDT...
Rows compared: 2,980,800
Columns: PASS
Timestamps: PASS
Numeric values: PASS
BTCUSDT: VALIDATION PASSED

Validating ETHUSDT...
Rows compared: 2,980,800
Columns: PASS
Timestamps: PASS
Numeric values: PASS
ETHUSDT: VALIDATION PASSED